/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tms.ui;

import javax.swing.JTextArea;

import javax.swing.table.DefaultTableModel;

import tms.business.AdminOperations;
import tms.business.TCopOperations;
import tms.business.impl.AdminOperationsImpl;

import tms.business.impl.TCopOperationsImpl;

import tms.entities.RoleMasterEO;
import tms.entities.UserMasterEO;
import tms.entities.VehicleDetailsEO;

/**
 *
 * @author reddirani.battuluri
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        this.setVisible(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdminPane = new javax.swing.JTabbedPane();
        UserPanel = new javax.swing.JPanel();
        jTabbedPane7 = new javax.swing.JTabbedPane();
        UpdateUser = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        SearchUserLabel = new javax.swing.JLabel();
        SearchUserField = new javax.swing.JTextField();
        SearchUserBtn = new javax.swing.JButton();
        UserDetailsTitle = new javax.swing.JLabel();
        UpdateUserLabel = new javax.swing.JLabel();
        UpdateUserPswdLabel = new javax.swing.JLabel();
        NewRoleLabel = new javax.swing.JLabel();
        UserNameField = new javax.swing.JTextField();
        UserPswdField = new javax.swing.JPasswordField();
        UserRoleCombo = new javax.swing.JComboBox<>();
        UserPswdEditBtn = new javax.swing.JButton();
        UpdateUserBtn = new javax.swing.JButton();
        UpdateUserCnclBtn = new javax.swing.JButton();
        DeleteUser = new javax.swing.JPanel();
        UsernameLabelInDeleteUser = new javax.swing.JLabel();
        UsernameFieldInDeleteUser = new javax.swing.JTextField();
        SearchBtnInDeleteUser = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TableInDeleteUser = new javax.swing.JTable();
        UserDetailsTitleInDeleteUser = new javax.swing.JLabel();
        DeleteExistingUser = new javax.swing.JButton();
        CancelBtnInDeleteUser = new javax.swing.JButton();
        ViewUsers = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        UsernameFieldInCreateUser = new javax.swing.JTextField();
        PswdFieldInCreateUser = new javax.swing.JTextField();
        RoleComboInCreateUser = new javax.swing.JComboBox<>();
        CreateUserBtn = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        RolePanel = new javax.swing.JPanel();
        ManageRoles = new javax.swing.JTabbedPane();
        CreateRole = new javax.swing.JPanel();
        RoleName = new javax.swing.JLabel();
        RoleNameField = new javax.swing.JTextField();
        RoleDescription = new javax.swing.JLabel();
        RoleDescField = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        CreateNewRole = new javax.swing.JButton();
        CancelBtn = new javax.swing.JButton();
        CreateRoleTitle = new javax.swing.JLabel();
        UpdateRole = new javax.swing.JPanel();
        UpdateRoleTitle = new javax.swing.JLabel();
        RoleNameUpdate = new javax.swing.JLabel();
        RoleNameFieldUpdate = new javax.swing.JTextField();
        RoleDescUpdate = new javax.swing.JLabel();
        RoleDescScroll = new javax.swing.JScrollPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        SearchRoleBtn = new javax.swing.JButton();
        RoleDescEditBtn = new javax.swing.JButton();
        UpdateBtn = new javax.swing.JButton();
        UpdateCancelBtn = new javax.swing.JButton();
        DeleteRole = new javax.swing.JPanel();
        DeleteRoleTitle = new javax.swing.JLabel();
        DeleteRoleNameLabel = new javax.swing.JLabel();
        DeleteRoleNameCombo = new javax.swing.JComboBox<>();
        RoleDeleteBtn = new javax.swing.JButton();
        RoleDeleteCancelBtn = new javax.swing.JButton();
        ViewRole = new javax.swing.JPanel();
        RoleDetailsTitle = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        UserNameFieldInViewUsers = new javax.swing.JTextField();
        SearchBtnInViewUsers = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AdminPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        AdminPane.setMinimumSize(new java.awt.Dimension(250, 250));

        SearchUserLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SearchUserLabel.setText("Username");

        SearchUserBtn.setBackground(new java.awt.Color(153, 153, 255));
        SearchUserBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SearchUserBtn.setForeground(new java.awt.Color(204, 0, 0));
        SearchUserBtn.setText("Search");
        SearchUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchUserBtnActionPerformed(evt);
            }
        });

        UserDetailsTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UserDetailsTitle.setForeground(new java.awt.Color(204, 0, 0));
        UserDetailsTitle.setText("User Details");

        UpdateUserLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        UpdateUserLabel.setText("Username");

        UpdateUserPswdLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        UpdateUserPswdLabel.setText("Password");

        NewRoleLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        NewRoleLabel.setText("New Role");
        
        UserNameField.setEditable(false);
        
        UserNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameFieldActionPerformed(evt);
            }
        });

        UserPswdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserPswdFieldActionPerformed(evt);
            }
        });

        UserRoleCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "RTO", "Cop", "Clerk" }));
        UserRoleCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserRoleComboActionPerformed(evt);
            }
        });

        UserPswdEditBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        UserPswdEditBtn.setForeground(new java.awt.Color(204, 0, 0));
        UserPswdEditBtn.setText("Edit");

        UpdateUserBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        UpdateUserBtn.setForeground(new java.awt.Color(204, 0, 51));
        UpdateUserBtn.setText("Update");
        UpdateUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateUserBtnActionPerformed(evt);
            }
        });

        UpdateUserCnclBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        UpdateUserCnclBtn.setForeground(new java.awt.Color(204, 0, 0));
        UpdateUserCnclBtn.setText("Cancel");
        UpdateUserCnclBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateUserCnclBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UpdateUserLayout = new javax.swing.GroupLayout(UpdateUser);
        UpdateUser.setLayout(UpdateUserLayout);
        UpdateUserLayout.setHorizontalGroup(
            UpdateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateUserLayout.createSequentialGroup()
                .addGroup(UpdateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UpdateUserLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(UpdateUserBtn)
                        .addGap(56, 56, 56)
                        .addComponent(UpdateUserCnclBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UpdateUserLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UpdateUserLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(UpdateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SearchUserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UpdateUserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UpdateUserPswdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NewRoleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(UpdateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UserNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(UpdateUserLayout.createSequentialGroup()
                                .addComponent(SearchUserField, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SearchUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(UserRoleCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(UpdateUserLayout.createSequentialGroup()
                                .addComponent(UserPswdField, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UserPswdEditBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(UpdateUserLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(UserDetailsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(377, Short.MAX_VALUE))
        );
        UpdateUserLayout.setVerticalGroup(
            UpdateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateUserLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(UpdateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchUserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchUserField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(UserDetailsTitle)
                .addGap(14, 14, 14)
                .addComponent(jLabel25)
                .addGap(17, 17, 17)
                .addGroup(UpdateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateUserLabel)
                    .addComponent(UserNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(UpdateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateUserPswdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserPswdField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserPswdEditBtn))
                .addGap(18, 18, 18)
                .addGroup(UpdateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewRoleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserRoleCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(UpdateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateUserBtn)
                    .addComponent(UpdateUserCnclBtn))
                .addContainerGap())
        );

        jTabbedPane7.addTab("Update", UpdateUser);

        UsernameLabelInDeleteUser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        UsernameLabelInDeleteUser.setText("Username");

        SearchBtnInDeleteUser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SearchBtnInDeleteUser.setText("Search");
        SearchBtnInDeleteUser.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        SearchBtnInDeleteUserActionPerformed(evt);
                    }
                });

        TableInDeleteUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Username", "Password", "Role"
            }
        ));
      //  TableInDeleteUser.setRowHeight(1, 30);
                 
        jScrollPane3.setViewportView(TableInDeleteUser);
        if (TableInDeleteUser.getColumnModel().getColumnCount() > 0) {
            TableInDeleteUser.getColumnModel().getColumn(0).setHeaderValue("Username");
            TableInDeleteUser.getColumnModel().getColumn(1).setHeaderValue("Password");
            TableInDeleteUser.getColumnModel().getColumn(2).setHeaderValue("Role");
            
        }

        UserDetailsTitleInDeleteUser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        UserDetailsTitleInDeleteUser.setText("User Details");

        DeleteExistingUser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DeleteExistingUser.setText("Delete");
        DeleteExistingUser.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        DeleteExistingUserActionPerformed(evt);
                    }
                });

        CancelBtnInDeleteUser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CancelBtnInDeleteUser.setText("Cancel");
        CancelBtnInDeleteUser.addActionListener(new java.awt.event.ActionListener() {
                   public void actionPerformed(java.awt.event.ActionEvent evt) {
                       CancelBtnInDeleteUserActionPerformed(evt);
                   }
               });

        javax.swing.GroupLayout DeleteUserLayout = new javax.swing.GroupLayout(DeleteUser);
        DeleteUser.setLayout(DeleteUserLayout);
        DeleteUserLayout.setHorizontalGroup(
            DeleteUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeleteUserLayout.createSequentialGroup()
                .addGroup(DeleteUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DeleteUserLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(UsernameLabelInDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(UsernameFieldInDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(SearchBtnInDeleteUser))
                    .addGroup(DeleteUserLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DeleteUserLayout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(UserDetailsTitleInDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DeleteUserLayout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(DeleteExistingUser, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(CancelBtnInDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DeleteUserLayout.setVerticalGroup(
            DeleteUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeleteUserLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(DeleteUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsernameLabelInDeleteUser)
                    .addComponent(UsernameFieldInDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchBtnInDeleteUser))
                .addGap(31, 31, 31)
                .addComponent(UserDetailsTitleInDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(DeleteUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeleteExistingUser)
                    .addComponent(CancelBtnInDeleteUser))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        jTabbedPane7.addTab("Delete", DeleteUser);

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel33.setText("User Details");

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
//                {null, null, null},
//                {null, null, null},
//                {null, null, null},
//                {null, null, null}
            },
            new String [] {
                "Username", "Password", "Role"
            }
        ));
        jScrollPane4.setViewportView(jTable4);
        if (jTable4.getColumnModel().getColumnCount() > 0) {
            jTable4.getColumnModel().getColumn(0).setHeaderValue("Username");
            jTable4.getColumnModel().getColumn(1).setHeaderValue("Password");
            jTable4.getColumnModel().getColumn(2).setHeaderValue("Role");
        }

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
               jLabel2.setText("Username");

               SearchBtnInViewUsers.setText("Search");
        SearchBtnInViewUsers.addActionListener(new java.awt.event.ActionListener() {
                   public void actionPerformed(java.awt.event.ActionEvent evt) {
                       SearchBtnInViewUsersActionPerformed(evt);
                   }
               });


               javax.swing.GroupLayout ViewUsersLayout = new javax.swing.GroupLayout(ViewUsers);
               ViewUsers.setLayout(ViewUsersLayout);
               ViewUsersLayout.setHorizontalGroup(
                   ViewUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(ViewUsersLayout.createSequentialGroup()
                       .addGroup(ViewUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addGroup(ViewUsersLayout.createSequentialGroup()
                               .addGap(281, 281, 281)
                               .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                           .addGroup(ViewUsersLayout.createSequentialGroup()
                               .addGap(68, 68, 68)
                               .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)))
                       .addContainerGap(177, Short.MAX_VALUE))
                   .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewUsersLayout.createSequentialGroup()
                       .addGap(0, 0, Short.MAX_VALUE)
                       .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                       .addComponent(UserNameFieldInViewUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                       .addComponent(SearchBtnInViewUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addGap(122, 122, 122))
               );
               ViewUsersLayout.setVerticalGroup(
                   ViewUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(ViewUsersLayout.createSequentialGroup()
                       .addGap(54, 54, 54)
                       .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addGap(24, 24, 24)
                       .addGroup(ViewUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                           .addComponent(jLabel2)
                           .addComponent(UserNameFieldInViewUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(SearchBtnInViewUsers))
                       .addGap(54, 54, 54)
                       .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addContainerGap(246, Short.MAX_VALUE))
               );

               jTabbedPane7.addTab("View", ViewUsers);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("Username");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("Password");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setText("Assign Role");

        RoleComboInCreateUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "RTO", "Cop", "Clerk" }));

        CreateUserBtn.setBackground(new java.awt.Color(255, 255, 255));
        CreateUserBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CreateUserBtn.setText("Create");
        CreateUserBtn.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        CreateUserBtnActionPerformed(evt);
                    }
                });

        jButton17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton17.setText("Cancel");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                            .addComponent(jLabel24))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(UsernameFieldInCreateUser)
                            .addComponent(PswdFieldInCreateUser)
                            .addComponent(RoleComboInCreateUser, 0, 150, Short.MAX_VALUE)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(CreateUserBtn)
                        .addGap(82, 82, 82)
                        .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(451, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsernameFieldInCreateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PswdFieldInCreateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(RoleComboInCreateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CreateUserBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        jTabbedPane7.addTab("Create", jPanel10);

        javax.swing.GroupLayout UserPanelLayout = new javax.swing.GroupLayout(UserPanel);
        UserPanel.setLayout(UserPanelLayout);
        UserPanelLayout.setHorizontalGroup(
            UserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane7)
                .addContainerGap())
        );
        UserPanelLayout.setVerticalGroup(
            UserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane7)
                .addContainerGap())
        );

        AdminPane.addTab("Manage Users", UserPanel);

        RoleName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RoleName.setText("Rolename");

        RoleDescription.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RoleDescription.setText("Role Description");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        RoleDescField.setViewportView(jScrollPane1);

        CreateNewRole.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CreateNewRole.setForeground(new java.awt.Color(204, 0, 51));
        CreateNewRole.setText("Create");
        CreateNewRole.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        CreateNewRoleActionPerformed(evt);
                    }
                });

        CancelBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CancelBtn.setForeground(new java.awt.Color(204, 0, 51));
        CancelBtn.setText("Cancel");

        CreateRoleTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CreateRoleTitle.setForeground(new java.awt.Color(255, 51, 51));
        CreateRoleTitle.setText("Create Role");

        javax.swing.GroupLayout CreateRoleLayout = new javax.swing.GroupLayout(CreateRole);
        CreateRole.setLayout(CreateRoleLayout);
        CreateRoleLayout.setHorizontalGroup(
            CreateRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateRoleLayout.createSequentialGroup()
                .addGroup(CreateRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CreateRoleLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addGroup(CreateRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RoleDescription)
                            .addComponent(RoleName, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(CreateRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RoleNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RoleDescField, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(CreateRoleLayout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(CreateNewRole)
                        .addGap(57, 57, 57)
                        .addComponent(CancelBtn))
                    .addGroup(CreateRoleLayout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(CreateRoleTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CreateRoleLayout.setVerticalGroup(
            CreateRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateRoleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CreateRoleTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(CreateRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(RoleNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RoleName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(CreateRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CreateRoleLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(RoleDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CreateRoleLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(RoleDescField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(CreateRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreateNewRole, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelBtn))
                .addGap(78, 78, 78))
        );

        ManageRoles.addTab("Create", CreateRole);

        UpdateRoleTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UpdateRoleTitle.setForeground(new java.awt.Color(255, 102, 102));
        UpdateRoleTitle.setText("Update Role");

        RoleNameUpdate.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        RoleNameUpdate.setText("Role Name");

        RoleDescUpdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RoleDescUpdate.setText("Role Description");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane5.setViewportView(jTextArea2);

        RoleDescScroll.setViewportView(jScrollPane5);

        SearchRoleBtn.setForeground(new java.awt.Color(204, 0, 0));
        SearchRoleBtn.setText("Search");
        SearchRoleBtn.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        SearchRoleBtnActionPerformed(evt);
                    }
                });

        RoleDescEditBtn.setForeground(new java.awt.Color(204, 51, 0));
        RoleDescEditBtn.setText("Edit");

        UpdateBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        UpdateBtn.setForeground(new java.awt.Color(204, 0, 0));
        UpdateBtn.setText("Update");
        UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        UpdateBtnActionPerformed(evt);
                    }
                });

        UpdateCancelBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        UpdateCancelBtn.setForeground(new java.awt.Color(204, 0, 0));
        UpdateCancelBtn.setText("Cancel");

        javax.swing.GroupLayout UpdateRoleLayout = new javax.swing.GroupLayout(UpdateRole);
        UpdateRole.setLayout(UpdateRoleLayout);
        UpdateRoleLayout.setHorizontalGroup(
            UpdateRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateRoleLayout.createSequentialGroup()
                .addGroup(UpdateRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UpdateRoleLayout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(UpdateBtn))
                    .addGroup(UpdateRoleLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(UpdateRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RoleNameUpdate)
                            .addComponent(RoleDescUpdate))
                        .addGap(30, 30, 30)
                        .addGroup(UpdateRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UpdateRoleTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(UpdateRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(UpdateRoleLayout.createSequentialGroup()
                                    .addComponent(RoleNameFieldUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(40, 40, 40)
                                    .addComponent(SearchRoleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(UpdateRoleLayout.createSequentialGroup()
                                    .addGroup(UpdateRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(UpdateCancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(RoleDescScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(RoleDescEditBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        UpdateRoleLayout.setVerticalGroup(
            UpdateRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateRoleLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(UpdateRoleTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(UpdateRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RoleNameUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RoleNameFieldUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchRoleBtn))
                .addGroup(UpdateRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UpdateRoleLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(RoleDescUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UpdateRoleLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(RoleDescScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UpdateRoleLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(RoleDescEditBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(UpdateRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateBtn)
                    .addComponent(UpdateCancelBtn))
                .addGap(63, 63, 63))
        );

        ManageRoles.addTab("Update", UpdateRole);

        DeleteRoleTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DeleteRoleTitle.setForeground(new java.awt.Color(255, 0, 0));
        DeleteRoleTitle.setText("Delete Role");

        DeleteRoleNameLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DeleteRoleNameLabel.setText("Role Name");

        DeleteRoleNameCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "RTO", "Cop", "Clerk" }));
        DeleteRoleNameCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteRoleNameComboActionPerformed(evt);
            }
        });

        RoleDeleteBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RoleDeleteBtn.setForeground(new java.awt.Color(204, 0, 51));
        RoleDeleteBtn.setText("Delete");
        RoleDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoleDeleteBtnActionPerformed(evt);
            }
        });

        RoleDeleteCancelBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RoleDeleteCancelBtn.setForeground(new java.awt.Color(204, 0, 51));
        RoleDeleteCancelBtn.setText("Cancel");
        RoleDeleteCancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoleDeleteCancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DeleteRoleLayout = new javax.swing.GroupLayout(DeleteRole);
        DeleteRole.setLayout(DeleteRoleLayout);
        DeleteRoleLayout.setHorizontalGroup(
            DeleteRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeleteRoleLayout.createSequentialGroup()
                .addGroup(DeleteRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DeleteRoleLayout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(DeleteRoleTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DeleteRoleLayout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addGroup(DeleteRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DeleteRoleNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RoleDeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(DeleteRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RoleDeleteCancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DeleteRoleNameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(379, Short.MAX_VALUE))
        );
        DeleteRoleLayout.setVerticalGroup(
            DeleteRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeleteRoleLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(DeleteRoleTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(DeleteRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeleteRoleNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteRoleNameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(DeleteRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RoleDeleteBtn)
                    .addComponent(RoleDeleteCancelBtn))
                .addContainerGap(182, Short.MAX_VALUE))
        );

        ManageRoles.addTab("Delete", DeleteRole);

        RoleDetailsTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RoleDetailsTitle.setForeground(new java.awt.Color(255, 0, 51));
        RoleDetailsTitle.setText("Role Details");
        
    jTable1.setModel(new javax.swing.table.DefaultTableModel(
               new Object [][] {

               },
               new String [] {
                   "Rolename", "RoleDesc"
               }
           ) {
               Class[] types = new Class [] {
                   java.lang.String.class, java.lang.String.class
               };

               public Class getColumnClass(int columnIndex) {
                   return types [columnIndex];
               }
           });
           jScrollPane2.setViewportView(jTable1);

           jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
           jLabel1.setText("Rolename");

           jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton1ActionPerformed(evt);
                    }
                });

           javax.swing.GroupLayout ViewRoleLayout = new javax.swing.GroupLayout(ViewRole);
           ViewRole.setLayout(ViewRoleLayout);
           ViewRoleLayout.setHorizontalGroup(
               ViewRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(ViewRoleLayout.createSequentialGroup()
                   .addGroup(ViewRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                       .addGroup(ViewRoleLayout.createSequentialGroup()
                           .addGap(63, 63, 63)
                           .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE))
                       .addGroup(ViewRoleLayout.createSequentialGroup()
                           .addGap(320, 320, 320)
                           .addComponent(RoleDetailsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                   .addContainerGap(104, Short.MAX_VALUE))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewRoleLayout.createSequentialGroup()
                   .addContainerGap()
                   .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                   .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addGap(18, 18, 18)
                   .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addGap(134, 134, 134))
           );
           ViewRoleLayout.setVerticalGroup(
               ViewRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(ViewRoleLayout.createSequentialGroup()
                   .addGap(49, 49, 49)
                   .addComponent(RoleDetailsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addGap(33, 33, 33)
                   .addGroup(ViewRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                       .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addComponent(jButton1))
                   .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                   .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addGap(126, 126, 126))
           );

           ManageRoles.addTab("View", ViewRole);

           javax.swing.GroupLayout RolePanelLayout = new javax.swing.GroupLayout(RolePanel);
           RolePanel.setLayout(RolePanelLayout);
           RolePanelLayout.setHorizontalGroup(
               RolePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(ManageRoles)
           );
           RolePanelLayout.setVerticalGroup(
               RolePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(ManageRoles)
           );

           AdminPane.addTab("Manage Roles", RolePanel);

           javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
           getContentPane().setLayout(layout);
           layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(AdminPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
           );
           layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(AdminPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
           );

           pack();
    }
   // </editor-fold>//GEN-END:initComponents

    private void DeleteRoleNameComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteRoleNameComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteRoleNameComboActionPerformed

    private void UserRoleComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserRoleComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserRoleComboActionPerformed

    private void UserPswdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserPswdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserPswdFieldActionPerformed
    private void UserNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserPswdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserPswdFieldActionPerformed
   

    private void SearchUserBtnActionPerformed(java.awt.event.ActionEvent evt) {                                              
          // TODO add your handling code here:
        String userName = SearchUserField.getText();

          AdminOperations admin = new AdminOperationsImpl();
         UserMasterEO userDetails = admin.findByUserName(userName);
          UserNameField.setEnabled(false);
          UserNameField.setText(userDetails.getUsername());
          UserPswdField.setText(userDetails.getPassword());
          UserRoleCombo.setSelectedItem(userDetails.getRole().getRoleName());     
      }
    
        
    private void UpdateUserBtnActionPerformed(java.awt.event.ActionEvent evt) {       
        
           // TODO add your handling code here:
          String userName =  UserNameField.getText();
          String updatedPassword = UserPswdField.getText();
          String updatedRole = (String)UserRoleCombo.getSelectedItem();
          
           UserMasterEO user = new UserMasterEO();
           user.setUsername(userName);
           user.setPassword(updatedPassword);
           RoleMasterEO role = new RoleMasterEO();
           role.setRoleName(updatedRole);
           user.setRole(role);
           
           AdminOperations admin = new AdminOperationsImpl();
           admin.updateUser(user);
           
           this.dispose(); 
       }
             private void UpdateUserCnclBtnActionPerformed(java.awt.event.ActionEvent evt) {
                     this.dispose(); 
                 }
    
    
    private void CreateUserBtnActionPerformed(java.awt.event.ActionEvent evt) {                                          
           // TODO add your handling code here:
           String userName =  UsernameFieldInCreateUser.getText();
           String updatedPassword = PswdFieldInCreateUser.getText();
           String updatedRole = (String)RoleComboInCreateUser.getSelectedItem();
           
            UserMasterEO user = new UserMasterEO();
            user.setUsername(userName);
            user.setPassword(updatedPassword);
            RoleMasterEO role = new RoleMasterEO();
            role.setRoleName(updatedRole);
            user.setRole(role);
            
            AdminOperations admin = new AdminOperationsImpl();
            admin.addNewUser(user);
            this.dispose();
       }   
    
    
    private void SearchBtnInDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String userName = UsernameFieldInDeleteUser.getText();

          AdminOperations admin = new AdminOperationsImpl();
         UserMasterEO userDetails = admin.findByUserName(userName);
        System.out.println(userDetails);
        String username = userDetails.getUsername();
        String password = userDetails.getPassword();
        String role =  userDetails.getRole().getRoleName();
        
        TableInDeleteUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {username, password, role}
            },
            new String [] {
                "Username", "Password", "Role"
            }
        ));
      //  this.dispose();
    }
    
    private void  DeleteExistingUserActionPerformed(java.awt.event.ActionEvent evt) {
        String userName = UsernameFieldInDeleteUser.getText();
        AdminOperations admin = new AdminOperationsImpl();
        admin.deleteExisitingUser(userName);
        this.dispose();
    }
    
    private void CancelBtnInDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {
            this.dispose();
        }
    
    private void SearchBtnInViewUsersActionPerformed(java.awt.event.ActionEvent evt) {
        String username = UserNameFieldInViewUsers.getText();
            AdminOperations admin = new AdminOperationsImpl();
            UserMasterEO user = admin.findByUserName(username);
            DefaultTableModel model = (DefaultTableModel)jTable4.getModel();
            RoleMasterEO role = user.getRole();
            String roleName = role.getRoleName();
            if (model.getRowCount() > 0) {
                // Remove existing row
                    model.removeRow(0);
            }     
                model.addRow(new Object[]{user.getUsername(),user.getPassword(),roleName});    
           
        }
        
    // Roles
    private void CreateNewRoleActionPerformed(java.awt.event.ActionEvent evt) {
            String roleName = RoleNameField.getText();
            JTextArea textArea = (JTextArea) jScrollPane1.getViewport().getView();
            String roleDesc =  textArea.getText();
            
            RoleMasterEO role = new RoleMasterEO();
            role.setRoleName(roleName);
            role.setRoleDesc(roleDesc);
            AdminOperations admin = new AdminOperationsImpl();
            admin.addNewRole(role);
            
            this.dispose(); 
        }
    
    
    private void CancelBtnActionPerformed(java.awt.event.ActionEvent evt) {
            this.dispose(); 
        }
    
    
    private void SearchRoleBtnActionPerformed(java.awt.event.ActionEvent evt) {
        String roleName = RoleNameFieldUpdate.getText();
            new RoleMasterEO();
           
            AdminOperations admin = new AdminOperationsImpl();
            RoleMasterEO role =  admin.findByRoleName(roleName);
            JTextArea textArea = (JTextArea) jScrollPane5.getViewport().getView();
            textArea.setText(role.getRoleDesc());
          //  this.dispose(); 
        }
        
    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {
            JTextArea textArea = (JTextArea) jScrollPane5.getViewport().getView();
            String roleDesc = textArea.getText();
            RoleMasterEO role = new RoleMasterEO();
            role.setRoleName( RoleNameFieldUpdate.getText());
            role.setRoleDesc(roleDesc);
            AdminOperations admin = new AdminOperationsImpl();
            admin.updateRole(role);
            this.dispose(); 
        }
    
    private void RoleDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {
        String roleName =(String) DeleteRoleNameCombo.getSelectedItem();
            AdminOperations admin = new AdminOperationsImpl();
            admin.deleteRole(roleName);
            this.dispose(); 
        }
    private void RoleDeleteCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {
            this.dispose(); 
        }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        String roleName = jTextField1.getText();
            AdminOperations admin = new AdminOperationsImpl();
            RoleMasterEO role = admin.findByRoleName(roleName);
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            if (model.getRowCount() > 0) {
                // Remove existing row
                model.removeRow(0);
            }
          model.addRow(new Object[]{role.getRoleName(),role.getRoleDesc()});    
        }
    
        
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane AdminPane;
    private javax.swing.JButton CancelBtn;
    private javax.swing.JButton CreateNewRole;
    private javax.swing.JPanel CreateRole;
    private javax.swing.JLabel CreateRoleTitle;
    private javax.swing.JPanel DeleteRole;
    private javax.swing.JComboBox<String> DeleteRoleNameCombo;
    private javax.swing.JLabel DeleteRoleNameLabel;
    private javax.swing.JLabel DeleteRoleTitle;
    private javax.swing.JPanel DeleteUser;
    private javax.swing.JTabbedPane ManageRoles;
    private javax.swing.JLabel NewRoleLabel;
    private javax.swing.JButton RoleDeleteBtn;
    private javax.swing.JButton RoleDeleteCancelBtn;
    private javax.swing.JButton RoleDescEditBtn;
    private javax.swing.JScrollPane RoleDescField;
    private javax.swing.JScrollPane RoleDescScroll;
    private javax.swing.JLabel RoleDescUpdate;
    private javax.swing.JLabel RoleDescription;
    private javax.swing.JLabel RoleDetailsTitle;
    private javax.swing.JLabel RoleName;
    private javax.swing.JTextField RoleNameField;
    private javax.swing.JTextField RoleNameFieldUpdate;
    private javax.swing.JLabel RoleNameUpdate;
    private javax.swing.JPanel RolePanel;
    private javax.swing.JButton SearchRoleBtn;
    private javax.swing.JButton SearchUserBtn;
    private javax.swing.JTextField SearchUserField;
    private javax.swing.JLabel SearchUserLabel;
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JButton UpdateCancelBtn;
    private javax.swing.JPanel UpdateRole;
    private javax.swing.JLabel UpdateRoleTitle;
    private javax.swing.JPanel UpdateUser;
    private javax.swing.JButton UpdateUserBtn;
    private javax.swing.JButton UpdateUserCnclBtn;
    private javax.swing.JLabel UpdateUserLabel;
    private javax.swing.JLabel UpdateUserPswdLabel;
    private javax.swing.JLabel UserDetailsTitle;
    private javax.swing.JTextField UserNameField;
    private javax.swing.JPanel UserPanel;
    private javax.swing.JButton UserPswdEditBtn;
    private javax.swing.JPasswordField UserPswdField;
    private javax.swing.JComboBox<String> UserRoleCombo;
    private javax.swing.JPanel ViewRole;
    private javax.swing.JPanel ViewUsers;
    private javax.swing.JButton CreateUserBtn;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton SearchBtnInDeleteUser;
    private javax.swing.JButton DeleteExistingUser;
    private javax.swing.JButton CancelBtnInDeleteUser;
    private javax.swing.JComboBox<String> RoleComboInCreateUser;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel UsernameLabelInDeleteUser;
    private javax.swing.JLabel UserDetailsTitleInDeleteUser;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane7;
    private javax.swing.JTable TableInDeleteUser;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField UsernameFieldInCreateUser;
    private javax.swing.JTextField PswdFieldInCreateUser;
    private javax.swing.JTextField UsernameFieldInDeleteUser;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField UserNameFieldInViewUsers;
    private javax.swing.JButton SearchBtnInViewUsers;
    // End of variables declaration//GEN-END:variables
}
