/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tms.ui;

import tms.business.AdminOperations;
import tms.business.impl.AdminOperationsImpl;

import tms.entities.UserMasterEO;
import tms.entities.RoleMasterEO;

/**
 *
 * @author reddirani.battuluri
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        TMSTitle = new javax.swing.JLabel();
        UserNameLabel = new javax.swing.JLabel();
        UserNameField = new javax.swing.JTextField();
        PasswordLable = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        LoginBtn = new javax.swing.JButton();
        RoleNameLable = new javax.swing.JLabel();
        RoleNameCombo = new javax.swing.JComboBox();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(null);

        TMSTitle.setBackground(new java.awt.Color(0, 0, 0));
        TMSTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TMSTitle.setText("  Traffic Management System");
        getContentPane().add(TMSTitle);
        TMSTitle.setBounds(89, 21, 220, 40);

        UserNameLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        UserNameLabel.setText("Username");
        getContentPane().add(UserNameLabel);
        UserNameLabel.setBounds(48, 104, 64, 15);

        UserNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameFieldActionPerformed(evt);
            }
        });
        getContentPane().add(UserNameField);
        UserNameField.setBounds(130, 98, 163, 29);

        PasswordLable.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        PasswordLable.setText("Password");
        getContentPane().add(PasswordLable);
        PasswordLable.setBounds(48, 154, 64, 15);
        getContentPane().add(PasswordField);
        PasswordField.setBounds(130, 148, 163, 29);

        LoginBtn.setBackground(new java.awt.Color(102, 102, 255));
        LoginBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LoginBtn.setForeground(new java.awt.Color(255, 255, 255));
        LoginBtn.setText("Login");
        LoginBtn.setOpaque(false);
        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });
        getContentPane().add(LoginBtn);
        LoginBtn.setBounds(170, 280, 73, 25);

        RoleNameLable.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RoleNameLable.setText("Rolename");
        getContentPane().add(RoleNameLable);
        RoleNameLable.setBounds(40, 200, 70, 20);

        RoleNameCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "RTO", "Clerk", "Cop" }));
        getContentPane().add(RoleNameCombo);
        RoleNameCombo.setBounds(130, 200, 160, 30);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void UserNameFieldActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        String enteredUserName = UserNameField.getText();
        String enteredPassword = PasswordField.getText();
        String chooseRole =(String) RoleNameCombo.getSelectedItem();
        System.out.println(enteredUserName + " " + enteredPassword + " " + chooseRole);
        RoleMasterEO role = new RoleMasterEO();
        role.setRoleName(chooseRole);
        UserMasterEO user = new UserMasterEO(enteredUserName,enteredPassword,role);
        AdminOperations admin = new AdminOperationsImpl();
        boolean loggedIn = admin.login(user);

        if (loggedIn) {
            // Redirect to the next screen or perform other actions for successful login
            System.out.println("Login successful");
            
            this.dispose();
            
            switch(chooseRole) {
            case "Admin" :Admin adminFrame = new Admin();
                                    break;
            case "RTO" : RTO rtoFrame = new RTO();
                                    break;
            case "Cop" : Cop copFrame = new Cop();
                                    break;
            case "Clerk" :Clerk clerkFrame = new Clerk();    
                                    break;
            }
            
        } else {
            // Show error message or perform other actions for failed login
            System.out.println("Login failed");
            this.dispose();
        }
//
//        this.dispose();
        
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton LoginBtn;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel PasswordLable;
    private javax.swing.JComboBox RoleNameCombo;
    private javax.swing.JLabel RoleNameLable;
    private javax.swing.JLabel TMSTitle;
    private javax.swing.JTextField UserNameField;
    private javax.swing.JLabel UserNameLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration                   
}
