/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tms.ui;

/**
 *
 * @author reddirani.battuluri
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdminPane = new javax.swing.JTabbedPane();
        UserPanel = new javax.swing.JPanel();
        jTabbedPane7 = new javax.swing.JTabbedPane();
        UpdateUser = new javax.swing.JPanel();
        SearchUserLabel = new javax.swing.JLabel();
        SearchUserField = new javax.swing.JTextField();
        SearchUserBtn = new javax.swing.JButton();
        UserDetailsTitle = new javax.swing.JLabel();
        UpdateUserLabel = new javax.swing.JLabel();
        UpdateUserPswdLabel = new javax.swing.JLabel();
        NewRoleLabel = new javax.swing.JLabel();
        UserNameField = new javax.swing.JTextField();
        UserPswdField = new javax.swing.JPasswordField();
        UserRoleCombo = new javax.swing.JComboBox<>();
        UpdateUserBtn = new javax.swing.JButton();
        UpdateUserCnclBtn = new javax.swing.JButton();
        DeleteUser = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jButton22 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel32 = new javax.swing.JLabel();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        ViewUsers = new javax.swing.JPanel();
        CreateUserTitle3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        UserDetailsTableInViewUser = new javax.swing.JTable();
        UsernameLableInCreateUser = new javax.swing.JLabel();
        UserNameFieldInViewUsers = new javax.swing.JTextField();
        SearchBtnInViewUsers = new javax.swing.JButton();
        SearchAllUsers = new javax.swing.JButton();
        CreateUser = new javax.swing.JPanel();
        UsernameLabelInCreateUser = new javax.swing.JLabel();
        PasswordLabelInCreateUser = new javax.swing.JLabel();
        AssignRoleLabelInCreateUser = new javax.swing.JLabel();
        UsernameFieldInCreateUser = new javax.swing.JTextField();
        PswdFieldInCreateUser = new javax.swing.JTextField();
        RoleComboInCreateUser = new javax.swing.JComboBox<>();
        CreateUserBtn = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        CreateUserTitle = new javax.swing.JLabel();
        RolePanel = new javax.swing.JPanel();
        ManageRoles = new javax.swing.JTabbedPane();
        CreateRole = new javax.swing.JPanel();
        RoleName = new javax.swing.JLabel();
        RoleNameField = new javax.swing.JTextField();
        RoleDescription = new javax.swing.JLabel();
        RoleDescField = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        CreateBtn = new javax.swing.JButton();
        CancelBtn = new javax.swing.JButton();
        CreateRoleTitle = new javax.swing.JLabel();
        UpdateRole = new javax.swing.JPanel();
        UpdateRoleTitle = new javax.swing.JLabel();
        RoleNameUpdate = new javax.swing.JLabel();
        RoleNameFieldUpdate = new javax.swing.JTextField();
        RoleDescUpdate = new javax.swing.JLabel();
        RoleDescScroll = new javax.swing.JScrollPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        SearchRoleBtn = new javax.swing.JButton();
        RoleDescEditBtn = new javax.swing.JButton();
        UpdateBtn = new javax.swing.JButton();
        UpdateCancelBtn = new javax.swing.JButton();
        DeleteRole = new javax.swing.JPanel();
        DeleteRoleTitle = new javax.swing.JLabel();
        DeleteRoleNameLabel = new javax.swing.JLabel();
        DeleteRoleNameCombo = new javax.swing.JComboBox<>();
        RoleDeleteBtn = new javax.swing.JButton();
        RoleDeleteCancelBtn = new javax.swing.JButton();
        ViewRole = new javax.swing.JPanel();
        RoleDetailsTitle = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        LogoutPanel = new javax.swing.JPanel();
        LogoutBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AdminPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        AdminPane.setMinimumSize(new java.awt.Dimension(250, 250));
        AdminPane.setPreferredSize(new java.awt.Dimension(2000, 1000));

        SearchUserLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SearchUserLabel.setText("Username");

        SearchUserField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        SearchUserBtn.setBackground(new java.awt.Color(153, 153, 255));
        SearchUserBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SearchUserBtn.setForeground(new java.awt.Color(204, 0, 0));
        SearchUserBtn.setText("Search");
        SearchUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchUserBtnActionPerformed(evt);
            }
        });

        UserDetailsTitle.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        UserDetailsTitle.setForeground(new java.awt.Color(204, 0, 0));
        UserDetailsTitle.setText("User Details");

        UpdateUserLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        UpdateUserLabel.setText("Username");

        UpdateUserPswdLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        UpdateUserPswdLabel.setText("Password");

        NewRoleLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        NewRoleLabel.setText("New Role");

        UserNameField.setEditable(false);
        UserNameField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        UserNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameFieldActionPerformed(evt);
            }
        });

        UserPswdField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        UserPswdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserPswdFieldActionPerformed(evt);
            }
        });

        UserRoleCombo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        UserRoleCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "RTO", "Cop", "Clerk" }));
        UserRoleCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserRoleComboActionPerformed(evt);
            }
        });

        UpdateUserBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        UpdateUserBtn.setForeground(new java.awt.Color(204, 0, 51));
        UpdateUserBtn.setText("Update");
        UpdateUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateUserBtnActionPerformed(evt);
            }
        });

        UpdateUserCnclBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        UpdateUserCnclBtn.setForeground(new java.awt.Color(204, 0, 0));
        UpdateUserCnclBtn.setText("Cancel");

        javax.swing.GroupLayout UpdateUserLayout = new javax.swing.GroupLayout(UpdateUser);
        UpdateUser.setLayout(UpdateUserLayout);
        UpdateUserLayout.setHorizontalGroup(
            UpdateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdateUserLayout.createSequentialGroup()
                .addGroup(UpdateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(UpdateUserLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(UpdateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdateUserLayout.createSequentialGroup()
                                .addComponent(UpdateUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(88, 88, 88))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdateUserLayout.createSequentialGroup()
                                .addGroup(UpdateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(NewRoleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(UpdateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(UpdateUserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(UpdateUserPswdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(111, 111, 111)))
                        .addComponent(UpdateUserCnclBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UpdateUserLayout.createSequentialGroup()
                        .addGap(0, 173, Short.MAX_VALUE)
                        .addGroup(UpdateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(UpdateUserLayout.createSequentialGroup()
                                .addComponent(SearchUserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(SearchUserField, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)
                                .addComponent(SearchUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(UpdateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(UserRoleCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(UserPswdField, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(UserNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(47, 47, 47))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdateUserLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(UserDetailsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140))
        );
        UpdateUserLayout.setVerticalGroup(
            UpdateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateUserLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(UpdateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchUserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchUserField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(128, 128, 128)
                .addComponent(UserDetailsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addGroup(UpdateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateUserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addGroup(UpdateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserPswdField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateUserPswdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(UpdateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UpdateUserLayout.createSequentialGroup()
                        .addComponent(NewRoleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                        .addGroup(UpdateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(UpdateUserCnclBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UpdateUserBtn)))
                    .addGroup(UpdateUserLayout.createSequentialGroup()
                        .addComponent(UserRoleCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane7.addTab("Update", UpdateUser);

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel31.setText("Username");

        jButton22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton22.setText("Search");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Username", "Password", "Role"
            }
        ));
        jScrollPane3.setViewportView(jTable3);
        if (jTable3.getColumnModel().getColumnCount() > 0) {
            jTable3.getColumnModel().getColumn(0).setHeaderValue("Username");
            jTable3.getColumnModel().getColumn(1).setHeaderValue("Password");
            jTable3.getColumnModel().getColumn(2).setHeaderValue("Role");
        }

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel32.setText("User Details");

        jButton23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton23.setText("Delete");

        jButton24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton24.setText("Cancel");

        javax.swing.GroupLayout DeleteUserLayout = new javax.swing.GroupLayout(DeleteUser);
        DeleteUser.setLayout(DeleteUserLayout);
        DeleteUserLayout.setHorizontalGroup(
            DeleteUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeleteUserLayout.createSequentialGroup()
                .addGroup(DeleteUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DeleteUserLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jButton22))
                    .addGroup(DeleteUserLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DeleteUserLayout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DeleteUserLayout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DeleteUserLayout.setVerticalGroup(
            DeleteUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeleteUserLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(DeleteUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton22))
                .addGap(31, 31, 31)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(DeleteUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton23)
                    .addComponent(jButton24))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane7.addTab("Delete", DeleteUser);

        CreateUserTitle3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        CreateUserTitle3.setForeground(new java.awt.Color(153, 0, 0));
        CreateUserTitle3.setText("User Details");

        UserDetailsTableInViewUser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        UserDetailsTableInViewUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Password", "Role"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(UserDetailsTableInViewUser);

        UsernameLableInCreateUser.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        UsernameLableInCreateUser.setText("Username");

        UserNameFieldInViewUsers.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        SearchBtnInViewUsers.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        SearchBtnInViewUsers.setForeground(new java.awt.Color(204, 0, 0));
        SearchBtnInViewUsers.setText("Search");

        SearchAllUsers.setText("Search All Users");

        javax.swing.GroupLayout ViewUsersLayout = new javax.swing.GroupLayout(ViewUsers);
        ViewUsers.setLayout(ViewUsersLayout);
        ViewUsersLayout.setHorizontalGroup(
            ViewUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewUsersLayout.createSequentialGroup()
                .addGroup(ViewUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewUsersLayout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(CreateUserTitle3, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ViewUsersLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(ViewUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ViewUsersLayout.createSequentialGroup()
                                .addComponent(UsernameLableInCreateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(UserNameFieldInViewUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(SearchBtnInViewUsers)
                                .addGap(28, 28, 28)
                                .addComponent(SearchAllUsers)))))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        ViewUsersLayout.setVerticalGroup(
            ViewUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewUsersLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(CreateUserTitle3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(ViewUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewUsersLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(ViewUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(UserNameFieldInViewUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UsernameLableInCreateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SearchBtnInViewUsers)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewUsersLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(SearchAllUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(137, 137, 137)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(315, Short.MAX_VALUE))
        );

        jTabbedPane7.addTab("View", ViewUsers);

        UsernameLabelInCreateUser.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        UsernameLabelInCreateUser.setText("Username");

        PasswordLabelInCreateUser.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        PasswordLabelInCreateUser.setText("Password");

        AssignRoleLabelInCreateUser.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        AssignRoleLabelInCreateUser.setText("Assign Role");

        UsernameFieldInCreateUser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        PswdFieldInCreateUser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        RoleComboInCreateUser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RoleComboInCreateUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "RTO", "Cop", "Clerk" }));

        CreateUserBtn.setBackground(new java.awt.Color(255, 255, 255));
        CreateUserBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CreateUserBtn.setForeground(new java.awt.Color(204, 0, 0));
        CreateUserBtn.setText("Create");

        jButton17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton17.setForeground(new java.awt.Color(204, 0, 0));
        jButton17.setText("Cancel");

        CreateUserTitle.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        CreateUserTitle.setForeground(new java.awt.Color(204, 0, 0));
        CreateUserTitle.setText("Create User");
        CreateUserTitle.setPreferredSize(new java.awt.Dimension(2000, 1000));

        javax.swing.GroupLayout CreateUserLayout = new javax.swing.GroupLayout(CreateUser);
        CreateUser.setLayout(CreateUserLayout);
        CreateUserLayout.setHorizontalGroup(
            CreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateUserLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(CreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreateUserLayout.createSequentialGroup()
                        .addGroup(CreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(CreateUserLayout.createSequentialGroup()
                                    .addComponent(CreateUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(79, 79, 79)
                                    .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(CreateUserLayout.createSequentialGroup()
                                    .addComponent(AssignRoleLabelInCreateUser)
                                    .addGap(42, 42, 42)
                                    .addComponent(RoleComboInCreateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(PasswordLabelInCreateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(442, 442, 442))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreateUserLayout.createSequentialGroup()
                        .addComponent(UsernameLabelInCreateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addGroup(CreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PswdFieldInCreateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UsernameFieldInCreateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(436, 436, 436))))
            .addGroup(CreateUserLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(CreateUserTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        CreateUserLayout.setVerticalGroup(
            CreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateUserLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(CreateUserTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(CreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsernameFieldInCreateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsernameLabelInCreateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(CreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PasswordLabelInCreateUser)
                    .addComponent(PswdFieldInCreateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(CreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AssignRoleLabelInCreateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RoleComboInCreateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(CreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreateUserBtn)
                    .addComponent(jButton17))
                .addContainerGap(384, Short.MAX_VALUE))
        );

        jTabbedPane7.addTab("Create", CreateUser);

        javax.swing.GroupLayout UserPanelLayout = new javax.swing.GroupLayout(UserPanel);
        UserPanel.setLayout(UserPanelLayout);
        UserPanelLayout.setHorizontalGroup(
            UserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane7)
        );
        UserPanelLayout.setVerticalGroup(
            UserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane7)
        );

        AdminPane.addTab("Manage Users", UserPanel);

        RoleName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RoleName.setText("Rolename");

        RoleDescription.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RoleDescription.setText("Role Description");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        RoleDescField.setViewportView(jScrollPane1);

        CreateBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CreateBtn.setForeground(new java.awt.Color(204, 0, 51));
        CreateBtn.setText("Create");
        CreateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateBtnActionPerformed(evt);
            }
        });

        CancelBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CancelBtn.setForeground(new java.awt.Color(204, 0, 51));
        CancelBtn.setText("Cancel");

        CreateRoleTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CreateRoleTitle.setForeground(new java.awt.Color(255, 51, 51));
        CreateRoleTitle.setText("Create Role");

        javax.swing.GroupLayout CreateRoleLayout = new javax.swing.GroupLayout(CreateRole);
        CreateRole.setLayout(CreateRoleLayout);
        CreateRoleLayout.setHorizontalGroup(
            CreateRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateRoleLayout.createSequentialGroup()
                .addGroup(CreateRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CreateRoleLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addGroup(CreateRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RoleDescription)
                            .addComponent(RoleName, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(CreateRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RoleNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RoleDescField, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(CreateRoleLayout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(CreateBtn)
                        .addGap(57, 57, 57)
                        .addComponent(CancelBtn))
                    .addGroup(CreateRoleLayout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(CreateRoleTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CreateRoleLayout.setVerticalGroup(
            CreateRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateRoleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CreateRoleTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(CreateRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(RoleNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RoleName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(CreateRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CreateRoleLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(RoleDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CreateRoleLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(RoleDescField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 447, Short.MAX_VALUE)
                .addGroup(CreateRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelBtn))
                .addGap(78, 78, 78))
        );

        ManageRoles.addTab("Create", CreateRole);

        UpdateRoleTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UpdateRoleTitle.setForeground(new java.awt.Color(255, 102, 102));
        UpdateRoleTitle.setText("Update Role");

        RoleNameUpdate.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        RoleNameUpdate.setText("Role Name");

        RoleDescUpdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RoleDescUpdate.setText("Role Description");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane5.setViewportView(jTextArea2);

        RoleDescScroll.setViewportView(jScrollPane5);

        SearchRoleBtn.setForeground(new java.awt.Color(204, 0, 0));
        SearchRoleBtn.setText("Search");

        RoleDescEditBtn.setForeground(new java.awt.Color(204, 51, 0));
        RoleDescEditBtn.setText("Edit");
        RoleDescEditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoleDescEditBtnActionPerformed(evt);
            }
        });

        UpdateBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        UpdateBtn.setForeground(new java.awt.Color(204, 0, 0));
        UpdateBtn.setText("Update");

        UpdateCancelBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        UpdateCancelBtn.setForeground(new java.awt.Color(204, 0, 0));
        UpdateCancelBtn.setText("Cancel");

        javax.swing.GroupLayout UpdateRoleLayout = new javax.swing.GroupLayout(UpdateRole);
        UpdateRole.setLayout(UpdateRoleLayout);
        UpdateRoleLayout.setHorizontalGroup(
            UpdateRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateRoleLayout.createSequentialGroup()
                .addGroup(UpdateRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UpdateRoleLayout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(UpdateBtn))
                    .addGroup(UpdateRoleLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(UpdateRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RoleNameUpdate)
                            .addComponent(RoleDescUpdate))
                        .addGap(30, 30, 30)
                        .addGroup(UpdateRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UpdateRoleTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(UpdateRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(UpdateRoleLayout.createSequentialGroup()
                                    .addComponent(RoleNameFieldUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(40, 40, 40)
                                    .addComponent(SearchRoleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(UpdateRoleLayout.createSequentialGroup()
                                    .addGroup(UpdateRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(UpdateCancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(RoleDescScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(RoleDescEditBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        UpdateRoleLayout.setVerticalGroup(
            UpdateRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateRoleLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(UpdateRoleTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(UpdateRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RoleNameUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RoleNameFieldUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchRoleBtn))
                .addGroup(UpdateRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UpdateRoleLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(RoleDescUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UpdateRoleLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(RoleDescScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UpdateRoleLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(RoleDescEditBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 434, Short.MAX_VALUE)
                .addGroup(UpdateRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateBtn)
                    .addComponent(UpdateCancelBtn))
                .addGap(63, 63, 63))
        );

        ManageRoles.addTab("Update", UpdateRole);

        DeleteRoleTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DeleteRoleTitle.setForeground(new java.awt.Color(255, 0, 0));
        DeleteRoleTitle.setText("Delete Role");

        DeleteRoleNameLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DeleteRoleNameLabel.setText("Role Name");

        DeleteRoleNameCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "RTO", "Cop", "Clerk" }));
        DeleteRoleNameCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteRoleNameComboActionPerformed(evt);
            }
        });

        RoleDeleteBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RoleDeleteBtn.setForeground(new java.awt.Color(204, 0, 51));
        RoleDeleteBtn.setText("Delete");

        RoleDeleteCancelBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RoleDeleteCancelBtn.setForeground(new java.awt.Color(204, 0, 51));
        RoleDeleteCancelBtn.setText("Cancel");

        javax.swing.GroupLayout DeleteRoleLayout = new javax.swing.GroupLayout(DeleteRole);
        DeleteRole.setLayout(DeleteRoleLayout);
        DeleteRoleLayout.setHorizontalGroup(
            DeleteRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeleteRoleLayout.createSequentialGroup()
                .addGroup(DeleteRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DeleteRoleLayout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(DeleteRoleTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DeleteRoleLayout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addGroup(DeleteRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DeleteRoleNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RoleDeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(DeleteRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RoleDeleteCancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DeleteRoleNameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(379, Short.MAX_VALUE))
        );
        DeleteRoleLayout.setVerticalGroup(
            DeleteRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeleteRoleLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(DeleteRoleTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(DeleteRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeleteRoleNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteRoleNameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(DeleteRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RoleDeleteBtn)
                    .addComponent(RoleDeleteCancelBtn))
                .addContainerGap(550, Short.MAX_VALUE))
        );

        ManageRoles.addTab("Delete", DeleteRole);

        RoleDetailsTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RoleDetailsTitle.setForeground(new java.awt.Color(255, 0, 51));
        RoleDetailsTitle.setText("Role Details");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rolename", "RoleDesc"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Rolename");

        jButton1.setText("Search");

        javax.swing.GroupLayout ViewRoleLayout = new javax.swing.GroupLayout(ViewRole);
        ViewRole.setLayout(ViewRoleLayout);
        ViewRoleLayout.setHorizontalGroup(
            ViewRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewRoleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134))
            .addGroup(ViewRoleLayout.createSequentialGroup()
                .addGroup(ViewRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewRoleLayout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(RoleDetailsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ViewRoleLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        ViewRoleLayout.setVerticalGroup(
            ViewRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewRoleLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(RoleDetailsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(ViewRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(152, 152, 152)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(301, Short.MAX_VALUE))
        );

        ManageRoles.addTab("View", ViewRole);

        javax.swing.GroupLayout RolePanelLayout = new javax.swing.GroupLayout(RolePanel);
        RolePanel.setLayout(RolePanelLayout);
        RolePanelLayout.setHorizontalGroup(
            RolePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ManageRoles)
        );
        RolePanelLayout.setVerticalGroup(
            RolePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ManageRoles)
        );

        AdminPane.addTab("Manage Roles", RolePanel);

        LogoutBtn.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        LogoutBtn.setForeground(new java.awt.Color(204, 0, 0));
        LogoutBtn.setText("Log Out");

        javax.swing.GroupLayout LogoutPanelLayout = new javax.swing.GroupLayout(LogoutPanel);
        LogoutPanel.setLayout(LogoutPanelLayout);
        LogoutPanelLayout.setHorizontalGroup(
            LogoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogoutPanelLayout.createSequentialGroup()
                .addContainerGap(264, Short.MAX_VALUE)
                .addComponent(LogoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(258, 258, 258))
        );
        LogoutPanelLayout.setVerticalGroup(
            LogoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoutPanelLayout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(LogoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(254, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LogoutPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(LogoutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 276, Short.MAX_VALUE))
        );

        AdminPane.addTab("Log Out", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AdminPane, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AdminPane, javax.swing.GroupLayout.DEFAULT_SIZE, 818, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteRoleNameComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteRoleNameComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteRoleNameComboActionPerformed

    private void UserRoleComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserRoleComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserRoleComboActionPerformed

    private void UserPswdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserPswdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserPswdFieldActionPerformed

    private void UserNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNameFieldActionPerformed

    private void SearchUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchUserBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchUserBtnActionPerformed

    private void CreateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreateBtnActionPerformed

    private void UpdateUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateUserBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateUserBtnActionPerformed

    private void RoleDescEditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoleDescEditBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RoleDescEditBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane AdminPane;
    private javax.swing.JLabel AssignRoleLabelInCreateUser;
    private javax.swing.JButton CancelBtn;
    private javax.swing.JButton CreateBtn;
    private javax.swing.JPanel CreateRole;
    private javax.swing.JLabel CreateRoleTitle;
    private javax.swing.JPanel CreateUser;
    private javax.swing.JButton CreateUserBtn;
    private javax.swing.JLabel CreateUserTitle;
    private javax.swing.JLabel CreateUserTitle3;
    private javax.swing.JPanel DeleteRole;
    private javax.swing.JComboBox<String> DeleteRoleNameCombo;
    private javax.swing.JLabel DeleteRoleNameLabel;
    private javax.swing.JLabel DeleteRoleTitle;
    private javax.swing.JPanel DeleteUser;
    private javax.swing.JButton LogoutBtn;
    private javax.swing.JPanel LogoutPanel;
    private javax.swing.JTabbedPane ManageRoles;
    private javax.swing.JLabel NewRoleLabel;
    private javax.swing.JLabel PasswordLabelInCreateUser;
    private javax.swing.JTextField PswdFieldInCreateUser;
    private javax.swing.JComboBox<String> RoleComboInCreateUser;
    private javax.swing.JButton RoleDeleteBtn;
    private javax.swing.JButton RoleDeleteCancelBtn;
    private javax.swing.JButton RoleDescEditBtn;
    private javax.swing.JScrollPane RoleDescField;
    private javax.swing.JScrollPane RoleDescScroll;
    private javax.swing.JLabel RoleDescUpdate;
    private javax.swing.JLabel RoleDescription;
    private javax.swing.JLabel RoleDetailsTitle;
    private javax.swing.JLabel RoleName;
    private javax.swing.JTextField RoleNameField;
    private javax.swing.JTextField RoleNameFieldUpdate;
    private javax.swing.JLabel RoleNameUpdate;
    private javax.swing.JPanel RolePanel;
    private javax.swing.JButton SearchAllUsers;
    private javax.swing.JButton SearchBtnInViewUsers;
    private javax.swing.JButton SearchRoleBtn;
    private javax.swing.JButton SearchUserBtn;
    private javax.swing.JTextField SearchUserField;
    private javax.swing.JLabel SearchUserLabel;
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JButton UpdateCancelBtn;
    private javax.swing.JPanel UpdateRole;
    private javax.swing.JLabel UpdateRoleTitle;
    private javax.swing.JPanel UpdateUser;
    private javax.swing.JButton UpdateUserBtn;
    private javax.swing.JButton UpdateUserCnclBtn;
    private javax.swing.JLabel UpdateUserLabel;
    private javax.swing.JLabel UpdateUserPswdLabel;
    private javax.swing.JTable UserDetailsTableInViewUser;
    private javax.swing.JLabel UserDetailsTitle;
    private javax.swing.JTextField UserNameField;
    private javax.swing.JTextField UserNameFieldInViewUsers;
    private javax.swing.JPanel UserPanel;
    private javax.swing.JPasswordField UserPswdField;
    private javax.swing.JComboBox<String> UserRoleCombo;
    private javax.swing.JTextField UsernameFieldInCreateUser;
    private javax.swing.JLabel UsernameLabelInCreateUser;
    private javax.swing.JLabel UsernameLableInCreateUser;
    private javax.swing.JPanel ViewRole;
    private javax.swing.JPanel ViewUsers;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane7;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField16;
    // End of variables declaration//GEN-END:variables
}
