/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tms.ui;

/**
 *
 * @author reddirani.battuluri
 */
public class Clerk extends javax.swing.JFrame {

    /**
     * Creates new form Clerk
     */
    public Clerk() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        ManageOffences = new javax.swing.JPanel();
        ManageOffencesTab = new javax.swing.JTabbedPane();
        RaiseOffenceTab = new javax.swing.JPanel();
        RaiseOffencePanel = new javax.swing.JPanel();
        VehicleNumLableInRaiseOffence = new javax.swing.JLabel();
        VehNumFieldInRaiseOffence = new javax.swing.JTextField();
        ImageLabelRaiseOffence = new javax.swing.JLabel();
        OffenceStatusLabelInRaiseOffence = new javax.swing.JLabel();
        OffenceStatusComboBoxInRaiseOffence = new javax.swing.JComboBox<>();
        OffenceIdLabelInRaiseOffence = new javax.swing.JLabel();
        OffenceIdFieldInRaiseOffence = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        PlaceLabelInRaiseOffence = new javax.swing.JLabel();
        PlaceFieldInRaiseOffence = new javax.swing.JTextField();
        ReportedByLabelInRaiseOffence = new javax.swing.JLabel();
        ReportedByFieldInRaiseOffence = new javax.swing.JTextField();
        RaiseBtnInRaiseOffence = new javax.swing.JButton();
        CancelBtnInRaiseOffence = new javax.swing.JButton();
        UploadBtnRaiseOffence = new javax.swing.JButton();
        OffenceDetailsTitle = new javax.swing.JLabel();
        ClearOffencePanel = new javax.swing.JPanel();
        ClearOffenceTitle = new javax.swing.JLabel();
        VehNumLableInClearOffence = new javax.swing.JLabel();
        VehNumFieldInClearOffence = new javax.swing.JTextField();
        SearchBtnInClearOffence = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        OffencesTableInClearOffence = new javax.swing.JTable();
        ClearBtnInClearOffence = new javax.swing.JButton();
        CancelBtnInClearOffence = new javax.swing.JButton();
        ViewOffenceTab = new javax.swing.JPanel();
        ViewOffencePanel = new javax.swing.JPanel();
        OffenceHistoryTitle = new javax.swing.JLabel();
        VehNoViewOffencesLabel = new javax.swing.JLabel();
        VehNumFielInViewOffence = new javax.swing.JTextField();
        SearchBtnInViewOffences = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        OffenceHistoryTabel = new javax.swing.JTable();
        SearchAllOffences = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        LogoutPannel = new javax.swing.JPanel();
        LogoutBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        RaiseOffencePanel.setPreferredSize(new java.awt.Dimension(2000, 1000));

        VehicleNumLableInRaiseOffence.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        VehicleNumLableInRaiseOffence.setText("Vehicle Number");

        ImageLabelRaiseOffence.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ImageLabelRaiseOffence.setText("Image");

        OffenceStatusLabelInRaiseOffence.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        OffenceStatusLabelInRaiseOffence.setText("Offence Status");

        OffenceStatusComboBoxInRaiseOffence.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Paid", "UnPaid" }));

        OffenceIdLabelInRaiseOffence.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        OffenceIdLabelInRaiseOffence.setText("Offence Id");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Time");

        jSpinner1.setModel(new javax.swing.SpinnerDateModel());

        PlaceLabelInRaiseOffence.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        PlaceLabelInRaiseOffence.setText("Place");

        ReportedByLabelInRaiseOffence.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ReportedByLabelInRaiseOffence.setText("Reported By");

        RaiseBtnInRaiseOffence.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        RaiseBtnInRaiseOffence.setForeground(new java.awt.Color(153, 0, 0));
        RaiseBtnInRaiseOffence.setText("Raise");

        CancelBtnInRaiseOffence.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        CancelBtnInRaiseOffence.setForeground(new java.awt.Color(153, 0, 0));
        CancelBtnInRaiseOffence.setText("Cancel");

        UploadBtnRaiseOffence.setText("Upload");

        OffenceDetailsTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        OffenceDetailsTitle.setForeground(new java.awt.Color(204, 0, 0));
        OffenceDetailsTitle.setText("Offence Details");

        javax.swing.GroupLayout RaiseOffencePanelLayout = new javax.swing.GroupLayout(RaiseOffencePanel);
        RaiseOffencePanel.setLayout(RaiseOffencePanelLayout);
        RaiseOffencePanelLayout.setHorizontalGroup(
            RaiseOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RaiseOffencePanelLayout.createSequentialGroup()
                .addGroup(RaiseOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RaiseOffencePanelLayout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addGroup(RaiseOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VehicleNumLableInRaiseOffence)
                            .addComponent(OffenceStatusLabelInRaiseOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OffenceIdLabelInRaiseOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PlaceLabelInRaiseOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ReportedByLabelInRaiseOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ImageLabelRaiseOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(RaiseOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(VehNumFieldInRaiseOffence)
                            .addComponent(OffenceStatusComboBoxInRaiseOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OffenceIdFieldInRaiseOffence)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(PlaceFieldInRaiseOffence)
                            .addComponent(ReportedByFieldInRaiseOffence)
                            .addComponent(UploadBtnRaiseOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(RaiseOffencePanelLayout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(RaiseBtnInRaiseOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(CancelBtnInRaiseOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RaiseOffencePanelLayout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(OffenceDetailsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(1458, Short.MAX_VALUE))
        );
        RaiseOffencePanelLayout.setVerticalGroup(
            RaiseOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RaiseOffencePanelLayout.createSequentialGroup()
                .addComponent(OffenceDetailsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(RaiseOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VehNumFieldInRaiseOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VehicleNumLableInRaiseOffence))
                .addGap(18, 18, 18)
                .addGroup(RaiseOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ImageLabelRaiseOffence)
                    .addComponent(UploadBtnRaiseOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RaiseOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OffenceStatusLabelInRaiseOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OffenceStatusComboBoxInRaiseOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RaiseOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OffenceIdLabelInRaiseOffence)
                    .addComponent(OffenceIdFieldInRaiseOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(RaiseOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(RaiseOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PlaceLabelInRaiseOffence)
                    .addComponent(PlaceFieldInRaiseOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RaiseOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReportedByLabelInRaiseOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReportedByFieldInRaiseOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RaiseOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RaiseBtnInRaiseOffence)
                    .addComponent(CancelBtnInRaiseOffence))
                .addContainerGap(587, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout RaiseOffenceTabLayout = new javax.swing.GroupLayout(RaiseOffenceTab);
        RaiseOffenceTab.setLayout(RaiseOffenceTabLayout);
        RaiseOffenceTabLayout.setHorizontalGroup(
            RaiseOffenceTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2000, Short.MAX_VALUE)
            .addGroup(RaiseOffenceTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(RaiseOffenceTabLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(RaiseOffencePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        RaiseOffenceTabLayout.setVerticalGroup(
            RaiseOffenceTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
            .addGroup(RaiseOffenceTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(RaiseOffenceTabLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(RaiseOffencePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        ManageOffencesTab.addTab("Raise Offence", RaiseOffenceTab);

        ClearOffenceTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ClearOffenceTitle.setForeground(new java.awt.Color(153, 0, 0));
        ClearOffenceTitle.setText("Clear Offences");

        VehNumLableInClearOffence.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        VehNumLableInClearOffence.setText("Vehicle Number");

        SearchBtnInClearOffence.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SearchBtnInClearOffence.setForeground(new java.awt.Color(153, 0, 0));
        SearchBtnInClearOffence.setText("Search");

        OffencesTableInClearOffence.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        OffencesTableInClearOffence.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Select", "Vehicle Number", "Image", "Offence Detail Id", "Offence Status", "Offence ID", "Time", "Place", "Reported By"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(OffencesTableInClearOffence);

        ClearBtnInClearOffence.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ClearBtnInClearOffence.setForeground(new java.awt.Color(153, 0, 0));
        ClearBtnInClearOffence.setText("Clear");

        CancelBtnInClearOffence.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        CancelBtnInClearOffence.setForeground(new java.awt.Color(204, 0, 0));
        CancelBtnInClearOffence.setText("Cancel");

        javax.swing.GroupLayout ClearOffencePanelLayout = new javax.swing.GroupLayout(ClearOffencePanel);
        ClearOffencePanel.setLayout(ClearOffencePanelLayout);
        ClearOffencePanelLayout.setHorizontalGroup(
            ClearOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClearOffencePanelLayout.createSequentialGroup()
                .addGroup(ClearOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ClearOffencePanelLayout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(ClearOffenceTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ClearOffencePanelLayout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(VehNumLableInClearOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VehNumFieldInClearOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SearchBtnInClearOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ClearOffencePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 883, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ClearOffencePanelLayout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(ClearBtnInClearOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(CancelBtnInClearOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(1107, Short.MAX_VALUE))
        );
        ClearOffencePanelLayout.setVerticalGroup(
            ClearOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClearOffencePanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(ClearOffenceTitle)
                .addGap(43, 43, 43)
                .addGroup(ClearOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VehNumLableInClearOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VehNumFieldInClearOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchBtnInClearOffence))
                .addGap(51, 51, 51)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 641, Short.MAX_VALUE)
                .addGroup(ClearOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClearBtnInClearOffence)
                    .addComponent(CancelBtnInClearOffence))
                .addGap(54, 54, 54))
        );

        ManageOffencesTab.addTab("Clear Offence", ClearOffencePanel);

        OffenceHistoryTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        OffenceHistoryTitle.setForeground(new java.awt.Color(204, 0, 0));
        OffenceHistoryTitle.setText("Offence History");

        VehNoViewOffencesLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        VehNoViewOffencesLabel.setText("Vehicle Number");

        VehNumFielInViewOffence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VehNumFielInViewOffenceActionPerformed(evt);
            }
        });

        SearchBtnInViewOffences.setText("Search");

        OffenceHistoryTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Vehicle Number", "Image", "Offence Detail Id", "Offence Status", "Offence Id", "Time", "Place", "Reported By"
            }
        ));
        jScrollPane6.setViewportView(OffenceHistoryTabel);

        SearchAllOffences.setText("Search All Offences");

        javax.swing.GroupLayout ViewOffencePanelLayout = new javax.swing.GroupLayout(ViewOffencePanel);
        ViewOffencePanel.setLayout(ViewOffencePanelLayout);
        ViewOffencePanelLayout.setHorizontalGroup(
            ViewOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewOffencePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6)
                .addContainerGap())
            .addGroup(ViewOffencePanelLayout.createSequentialGroup()
                .addGap(317, 317, 317)
                .addComponent(OffenceHistoryTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(ViewOffencePanelLayout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(VehNoViewOffencesLabel)
                .addGap(33, 33, 33)
                .addComponent(VehNumFielInViewOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SearchBtnInViewOffences, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                .addComponent(SearchAllOffences, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        ViewOffencePanelLayout.setVerticalGroup(
            ViewOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewOffencePanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(OffenceHistoryTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(ViewOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VehNoViewOffencesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VehNumFielInViewOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchBtnInViewOffences)
                    .addComponent(SearchAllOffences, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(176, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ViewOffenceTabLayout = new javax.swing.GroupLayout(ViewOffenceTab);
        ViewOffenceTab.setLayout(ViewOffenceTabLayout);
        ViewOffenceTabLayout.setHorizontalGroup(
            ViewOffenceTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewOffenceTabLayout.createSequentialGroup()
                .addContainerGap(597, Short.MAX_VALUE)
                .addComponent(ViewOffencePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(482, 482, 482))
        );
        ViewOffenceTabLayout.setVerticalGroup(
            ViewOffenceTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewOffenceTabLayout.createSequentialGroup()
                .addGap(298, 298, 298)
                .addComponent(ViewOffencePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(253, Short.MAX_VALUE))
        );

        ManageOffencesTab.addTab("ViewOffences", ViewOffenceTab);

        javax.swing.GroupLayout ManageOffencesLayout = new javax.swing.GroupLayout(ManageOffences);
        ManageOffences.setLayout(ManageOffencesLayout);
        ManageOffencesLayout.setHorizontalGroup(
            ManageOffencesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ManageOffencesTab)
        );
        ManageOffencesLayout.setVerticalGroup(
            ManageOffencesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ManageOffencesTab, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jTabbedPane1.addTab("Manage Offences", ManageOffences);

        LogoutBtn.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        LogoutBtn.setForeground(new java.awt.Color(204, 0, 0));
        LogoutBtn.setText("Log Out");

        javax.swing.GroupLayout LogoutPannelLayout = new javax.swing.GroupLayout(LogoutPannel);
        LogoutPannel.setLayout(LogoutPannelLayout);
        LogoutPannelLayout.setHorizontalGroup(
            LogoutPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoutPannelLayout.createSequentialGroup()
                .addGap(380, 380, 380)
                .addComponent(LogoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(265, Short.MAX_VALUE))
        );
        LogoutPannelLayout.setVerticalGroup(
            LogoutPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoutPannelLayout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(LogoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(193, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LogoutPannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1152, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LogoutPannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(520, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Log Out", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VehNumFielInViewOffenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VehNumFielInViewOffenceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VehNumFielInViewOffenceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clerk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clerk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clerk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clerk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clerk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelBtnInClearOffence;
    private javax.swing.JButton CancelBtnInRaiseOffence;
    private javax.swing.JButton ClearBtnInClearOffence;
    private javax.swing.JPanel ClearOffencePanel;
    private javax.swing.JLabel ClearOffenceTitle;
    private javax.swing.JLabel ImageLabelRaiseOffence;
    private javax.swing.JButton LogoutBtn;
    private javax.swing.JPanel LogoutPannel;
    private javax.swing.JPanel ManageOffences;
    private javax.swing.JTabbedPane ManageOffencesTab;
    private javax.swing.JLabel OffenceDetailsTitle;
    private javax.swing.JTable OffenceHistoryTabel;
    private javax.swing.JLabel OffenceHistoryTitle;
    private javax.swing.JTextField OffenceIdFieldInRaiseOffence;
    private javax.swing.JLabel OffenceIdLabelInRaiseOffence;
    private javax.swing.JComboBox<String> OffenceStatusComboBoxInRaiseOffence;
    private javax.swing.JLabel OffenceStatusLabelInRaiseOffence;
    private javax.swing.JTable OffencesTableInClearOffence;
    private javax.swing.JTextField PlaceFieldInRaiseOffence;
    private javax.swing.JLabel PlaceLabelInRaiseOffence;
    private javax.swing.JButton RaiseBtnInRaiseOffence;
    private javax.swing.JPanel RaiseOffencePanel;
    private javax.swing.JPanel RaiseOffenceTab;
    private javax.swing.JTextField ReportedByFieldInRaiseOffence;
    private javax.swing.JLabel ReportedByLabelInRaiseOffence;
    private javax.swing.JButton SearchAllOffences;
    private javax.swing.JButton SearchBtnInClearOffence;
    private javax.swing.JButton SearchBtnInViewOffences;
    private javax.swing.JButton UploadBtnRaiseOffence;
    private javax.swing.JLabel VehNoViewOffencesLabel;
    private javax.swing.JTextField VehNumFielInViewOffence;
    private javax.swing.JTextField VehNumFieldInClearOffence;
    private javax.swing.JTextField VehNumFieldInRaiseOffence;
    private javax.swing.JLabel VehNumLableInClearOffence;
    private javax.swing.JLabel VehicleNumLableInRaiseOffence;
    private javax.swing.JPanel ViewOffencePanel;
    private javax.swing.JPanel ViewOffenceTab;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
