/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tms.ui;

/**
 *
 * @author reddirani.battuluri
 */
public class Cop extends javax.swing.JFrame {

    /**
     * Creates new form Cop
     */
    public Cop() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        VehicleDetailsCop = new javax.swing.JTabbedPane();
        ManageOffences = new javax.swing.JPanel();
        ManageOffenceTab = new javax.swing.JTabbedPane();
        RaiseOffencePanel = new javax.swing.JPanel();
        VehNumLabelInRaiseOffence = new javax.swing.JLabel();
        VehNumFieldInRaiseOffence = new javax.swing.JTextField();
        ImageLabelInRaiseOffence = new javax.swing.JLabel();
        OffenceStatusLabelInRaiseOffence = new javax.swing.JLabel();
        OffenceStatusComboBoxInRaiseOffence = new javax.swing.JComboBox<>();
        OffenceIdLabelInRaiseOffence = new javax.swing.JLabel();
        OffenceIdFieldInRaiseOffence = new javax.swing.JTextField();
        TimeLabelInRaiseOffence = new javax.swing.JLabel();
        TimeSpinnerInRaiseOffence = new javax.swing.JSpinner();
        PlaceLabelInRaiseOffence = new javax.swing.JLabel();
        PlaceFieldInRaiseOffence = new javax.swing.JTextField();
        ReportedByLabelInRaiseOffence = new javax.swing.JLabel();
        ReportedByFieldInRaiseOffence = new javax.swing.JTextField();
        RaiseOffenceBtn = new javax.swing.JButton();
        CancelOffenceBtn = new javax.swing.JButton();
        UploadImageBtn = new javax.swing.JButton();
        OffenceDetailsTitleInRaiseOffence = new javax.swing.JLabel();
        ClearOffenceTab = new javax.swing.JPanel();
        ClearOffencePanel = new javax.swing.JPanel();
        ClearOffenceTitle = new javax.swing.JLabel();
        VehNumLabelInClearOffence = new javax.swing.JLabel();
        VehNumFieldInClearOffence = new javax.swing.JTextField();
        SearchBtnInClearOffence = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ClearOffenceTable = new javax.swing.JTable();
        ClearOffenceBtn = new javax.swing.JButton();
        CancelBtnInClearOffence = new javax.swing.JButton();
        ViewOffencePanel = new javax.swing.JPanel();
        ViewOffencesTitle = new javax.swing.JLabel();
        VehicleNumLabelInViewOffence = new javax.swing.JLabel();
        VehicleNumFieldInViewOffence = new javax.swing.JTextField();
        SearchBtnInViewOffence = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        OffencesTableInViewOffence = new javax.swing.JTable();
        OwnerDetails = new javax.swing.JPanel();
        OwnerDetailsPane = new javax.swing.JTabbedPane();
        OwnerDetailsPanel = new javax.swing.JPanel();
        OwnerDetailsTitle = new javax.swing.JLabel();
        VehicleNumLabelInOwnerDetails = new javax.swing.JLabel();
        VehicleNumFieldInOwnerDetails = new javax.swing.JTextField();
        SearchBtnInOwnerDetails = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        OwnerDetailsTable = new javax.swing.JTable();
        ViewVehicles = new javax.swing.JPanel();
        ViewVehicleTab = new javax.swing.JTabbedPane();
        ViewVehicleDetailsPanel = new javax.swing.JPanel();
        VehicleDetailsTitle = new javax.swing.JLabel();
        VehNumLabelInViewVehicles = new javax.swing.JLabel();
        VehNumFieldInViewVehicles = new javax.swing.JTextField();
        SearchBtnInViewVehicles = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        VehicleDetailsTableInViewVehicles = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Vehicle Number", "Image", "Offence Detail Id", "Offence Status", "Offence Id", "Time", "Place", "Reported By"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        VehicleDetailsCop.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        VehNumLabelInRaiseOffence.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        VehNumLabelInRaiseOffence.setText("Vehicle Number");

        ImageLabelInRaiseOffence.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ImageLabelInRaiseOffence.setText("Image");

        OffenceStatusLabelInRaiseOffence.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        OffenceStatusLabelInRaiseOffence.setText("Offence Status");

        OffenceStatusComboBoxInRaiseOffence.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Paid", "UnPaid" }));

        OffenceIdLabelInRaiseOffence.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        OffenceIdLabelInRaiseOffence.setText("Offence Id");

        TimeLabelInRaiseOffence.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TimeLabelInRaiseOffence.setText("Time");

        TimeSpinnerInRaiseOffence.setModel(new javax.swing.SpinnerDateModel());

        PlaceLabelInRaiseOffence.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        PlaceLabelInRaiseOffence.setText("Place");

        PlaceFieldInRaiseOffence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlaceFieldInRaiseOffenceActionPerformed(evt);
            }
        });

        ReportedByLabelInRaiseOffence.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ReportedByLabelInRaiseOffence.setText("Reported By");

        RaiseOffenceBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        RaiseOffenceBtn.setForeground(new java.awt.Color(153, 0, 0));
        RaiseOffenceBtn.setText("Raise");

        CancelOffenceBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        CancelOffenceBtn.setForeground(new java.awt.Color(153, 0, 0));
        CancelOffenceBtn.setText("Cancel");

        UploadImageBtn.setText("Upload");

        OffenceDetailsTitleInRaiseOffence.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        OffenceDetailsTitleInRaiseOffence.setForeground(new java.awt.Color(204, 0, 0));
        OffenceDetailsTitleInRaiseOffence.setText("Offence Details");

        javax.swing.GroupLayout RaiseOffencePanelLayout = new javax.swing.GroupLayout(RaiseOffencePanel);
        RaiseOffencePanel.setLayout(RaiseOffencePanelLayout);
        RaiseOffencePanelLayout.setHorizontalGroup(
            RaiseOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RaiseOffencePanelLayout.createSequentialGroup()
                .addGroup(RaiseOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RaiseOffencePanelLayout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addGroup(RaiseOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VehNumLabelInRaiseOffence)
                            .addComponent(OffenceStatusLabelInRaiseOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OffenceIdLabelInRaiseOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TimeLabelInRaiseOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PlaceLabelInRaiseOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ReportedByLabelInRaiseOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ImageLabelInRaiseOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(RaiseOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(VehNumFieldInRaiseOffence)
                            .addComponent(OffenceStatusComboBoxInRaiseOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OffenceIdFieldInRaiseOffence)
                            .addComponent(TimeSpinnerInRaiseOffence, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(PlaceFieldInRaiseOffence)
                            .addComponent(ReportedByFieldInRaiseOffence)
                            .addComponent(UploadImageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(RaiseOffencePanelLayout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(RaiseOffenceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(CancelOffenceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RaiseOffencePanelLayout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(OffenceDetailsTitleInRaiseOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RaiseOffencePanelLayout.setVerticalGroup(
            RaiseOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RaiseOffencePanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(OffenceDetailsTitleInRaiseOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(RaiseOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VehNumLabelInRaiseOffence)
                    .addComponent(VehNumFieldInRaiseOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RaiseOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ImageLabelInRaiseOffence)
                    .addComponent(UploadImageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RaiseOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OffenceStatusLabelInRaiseOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OffenceStatusComboBoxInRaiseOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RaiseOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OffenceIdLabelInRaiseOffence)
                    .addComponent(OffenceIdFieldInRaiseOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(RaiseOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TimeLabelInRaiseOffence)
                    .addComponent(TimeSpinnerInRaiseOffence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(RaiseOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PlaceLabelInRaiseOffence)
                    .addComponent(PlaceFieldInRaiseOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RaiseOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReportedByLabelInRaiseOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReportedByFieldInRaiseOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RaiseOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RaiseOffenceBtn)
                    .addComponent(CancelOffenceBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ManageOffenceTab.addTab("Raise Offence", RaiseOffencePanel);

        ClearOffenceTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ClearOffenceTitle.setForeground(new java.awt.Color(153, 0, 0));
        ClearOffenceTitle.setText("Clear Offences");

        VehNumLabelInClearOffence.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        VehNumLabelInClearOffence.setText("Vehicle Number");

        SearchBtnInClearOffence.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SearchBtnInClearOffence.setForeground(new java.awt.Color(153, 0, 0));
        SearchBtnInClearOffence.setText("Search");

        ClearOffenceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Select", "Vehicle Number", "Image", "Offence Detail Id", "Offence Status", "Offence ID", "Time", "Place", "Reported By"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(ClearOffenceTable);

        ClearOffenceBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ClearOffenceBtn.setForeground(new java.awt.Color(153, 0, 0));
        ClearOffenceBtn.setText("Clear");

        CancelBtnInClearOffence.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        CancelBtnInClearOffence.setForeground(new java.awt.Color(204, 0, 0));
        CancelBtnInClearOffence.setText("Cancel");

        javax.swing.GroupLayout ClearOffencePanelLayout = new javax.swing.GroupLayout(ClearOffencePanel);
        ClearOffencePanel.setLayout(ClearOffencePanelLayout);
        ClearOffencePanelLayout.setHorizontalGroup(
            ClearOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClearOffencePanelLayout.createSequentialGroup()
                .addGroup(ClearOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ClearOffencePanelLayout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(ClearOffenceTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ClearOffencePanelLayout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(VehNumLabelInClearOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VehNumFieldInClearOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SearchBtnInClearOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ClearOffencePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 883, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ClearOffencePanelLayout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(ClearOffenceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(CancelBtnInClearOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        ClearOffencePanelLayout.setVerticalGroup(
            ClearOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClearOffencePanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(ClearOffenceTitle)
                .addGap(43, 43, 43)
                .addGroup(ClearOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VehNumLabelInClearOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VehNumFieldInClearOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchBtnInClearOffence))
                .addGap(51, 51, 51)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(ClearOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClearOffenceBtn)
                    .addComponent(CancelBtnInClearOffence))
                .addGap(54, 54, 54))
        );

        javax.swing.GroupLayout ClearOffenceTabLayout = new javax.swing.GroupLayout(ClearOffenceTab);
        ClearOffenceTab.setLayout(ClearOffenceTabLayout);
        ClearOffenceTabLayout.setHorizontalGroup(
            ClearOffenceTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(ClearOffenceTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ClearOffenceTabLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ClearOffencePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        ClearOffenceTabLayout.setVerticalGroup(
            ClearOffenceTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(ClearOffenceTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ClearOffenceTabLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ClearOffencePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        ManageOffenceTab.addTab("Clear Offence", ClearOffenceTab);

        ViewOffencePanel.setPreferredSize(new java.awt.Dimension(2000, 1000));

        ViewOffencesTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ViewOffencesTitle.setForeground(new java.awt.Color(204, 0, 0));
        ViewOffencesTitle.setText("View Offences");

        VehicleNumLabelInViewOffence.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        VehicleNumLabelInViewOffence.setText("Vehicle Number");

        VehicleNumFieldInViewOffence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VehicleNumFieldInViewOffenceActionPerformed(evt);
            }
        });

        SearchBtnInViewOffence.setText("Search");

        OffencesTableInViewOffence.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vehicle Number", "Image", "Offence Detail Id", "Offence Status", "Offence Id", "Time", "Place", "Reported By"
            }
        ));
        jScrollPane5.setViewportView(OffencesTableInViewOffence);

        javax.swing.GroupLayout ViewOffencePanelLayout = new javax.swing.GroupLayout(ViewOffencePanel);
        ViewOffencePanel.setLayout(ViewOffencePanelLayout);
        ViewOffencePanelLayout.setHorizontalGroup(
            ViewOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewOffencePanelLayout.createSequentialGroup()
                .addGroup(ViewOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewOffencePanelLayout.createSequentialGroup()
                        .addGroup(ViewOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ViewOffencePanelLayout.createSequentialGroup()
                                .addGap(264, 264, 264)
                                .addComponent(ViewOffencesTitle))
                            .addGroup(ViewOffencePanelLayout.createSequentialGroup()
                                .addGap(198, 198, 198)
                                .addComponent(VehicleNumLabelInViewOffence)
                                .addGap(31, 31, 31)
                                .addComponent(VehicleNumFieldInViewOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(SearchBtnInViewOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 348, Short.MAX_VALUE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 911, Short.MAX_VALUE))
                .addContainerGap())
        );
        ViewOffencePanelLayout.setVerticalGroup(
            ViewOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewOffencePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ViewOffencesTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(ViewOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VehicleNumLabelInViewOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchBtnInViewOffence)
                    .addComponent(VehicleNumFieldInViewOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(222, Short.MAX_VALUE))
        );

        ManageOffenceTab.addTab("View Offences", ViewOffencePanel);

        javax.swing.GroupLayout ManageOffencesLayout = new javax.swing.GroupLayout(ManageOffences);
        ManageOffences.setLayout(ManageOffencesLayout);
        ManageOffencesLayout.setHorizontalGroup(
            ManageOffencesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ManageOffenceTab)
        );
        ManageOffencesLayout.setVerticalGroup(
            ManageOffencesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ManageOffenceTab)
        );

        VehicleDetailsCop.addTab("Manage Offences", ManageOffences);

        OwnerDetailsTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        OwnerDetailsTitle.setForeground(new java.awt.Color(204, 0, 0));
        OwnerDetailsTitle.setText("Owner Details");

        VehicleNumLabelInOwnerDetails.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        VehicleNumLabelInOwnerDetails.setText("Vehicle Number");

        SearchBtnInOwnerDetails.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SearchBtnInOwnerDetails.setForeground(new java.awt.Color(153, 0, 0));
        SearchBtnInOwnerDetails.setText("Search");

        OwnerDetailsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Owner Id", "First Name", "Last Name", "Date of Birth", "Landline Number", "Mobile Number", "Gender", "Temporary Address", "Permanent Address", "Pincode", "Occupation", "Pancard Number", "Proof"
            }
        ));
        jScrollPane3.setViewportView(OwnerDetailsTable);

        javax.swing.GroupLayout OwnerDetailsPanelLayout = new javax.swing.GroupLayout(OwnerDetailsPanel);
        OwnerDetailsPanel.setLayout(OwnerDetailsPanelLayout);
        OwnerDetailsPanelLayout.setHorizontalGroup(
            OwnerDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OwnerDetailsPanelLayout.createSequentialGroup()
                .addGroup(OwnerDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OwnerDetailsPanelLayout.createSequentialGroup()
                        .addGroup(OwnerDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(OwnerDetailsPanelLayout.createSequentialGroup()
                                .addGap(285, 285, 285)
                                .addComponent(OwnerDetailsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(OwnerDetailsPanelLayout.createSequentialGroup()
                                .addGap(277, 277, 277)
                                .addComponent(VehicleNumLabelInOwnerDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(VehicleNumFieldInOwnerDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SearchBtnInOwnerDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 266, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        OwnerDetailsPanelLayout.setVerticalGroup(
            OwnerDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OwnerDetailsPanelLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(OwnerDetailsTitle)
                .addGap(63, 63, 63)
                .addGroup(OwnerDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VehicleNumLabelInOwnerDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VehicleNumFieldInOwnerDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchBtnInOwnerDetails))
                .addGap(72, 72, 72)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        OwnerDetailsPane.addTab("View Owner", OwnerDetailsPanel);

        javax.swing.GroupLayout OwnerDetailsLayout = new javax.swing.GroupLayout(OwnerDetails);
        OwnerDetails.setLayout(OwnerDetailsLayout);
        OwnerDetailsLayout.setHorizontalGroup(
            OwnerDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(OwnerDetailsPane)
        );
        OwnerDetailsLayout.setVerticalGroup(
            OwnerDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(OwnerDetailsPane)
        );

        VehicleDetailsCop.addTab("Owner Details", OwnerDetails);

        VehicleDetailsTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        VehicleDetailsTitle.setForeground(new java.awt.Color(153, 0, 0));
        VehicleDetailsTitle.setText("Vehicle Details");

        VehNumLabelInViewVehicles.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        VehNumLabelInViewVehicles.setText("Vehicle Number");

        SearchBtnInViewVehicles.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SearchBtnInViewVehicles.setForeground(new java.awt.Color(204, 0, 0));
        SearchBtnInViewVehicles.setText("Search");

        VehicleDetailsTableInViewVehicles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Vehicle ID", "Vehicle Type", "Engine Number", "Model Number", "Vehicle Name", "Vehicle Color", "Manufacturer Name", "Date of Manufacture", "Number of Cylinders", "Cubic Capacity", "Fuel Used", "Chassis Number"
            }
        ));
        jScrollPane1.setViewportView(VehicleDetailsTableInViewVehicles);

        javax.swing.GroupLayout ViewVehicleDetailsPanelLayout = new javax.swing.GroupLayout(ViewVehicleDetailsPanel);
        ViewVehicleDetailsPanel.setLayout(ViewVehicleDetailsPanelLayout);
        ViewVehicleDetailsPanelLayout.setHorizontalGroup(
            ViewVehicleDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewVehicleDetailsPanelLayout.createSequentialGroup()
                .addGap(527, 527, 527)
                .addGroup(ViewVehicleDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VehicleDetailsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ViewVehicleDetailsPanelLayout.createSequentialGroup()
                        .addComponent(VehNumLabelInViewVehicles, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(VehNumFieldInViewVehicles, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SearchBtnInViewVehicles, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewVehicleDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );
        ViewVehicleDetailsPanelLayout.setVerticalGroup(
            ViewVehicleDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewVehicleDetailsPanelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(VehicleDetailsTitle)
                .addGap(52, 52, 52)
                .addGroup(ViewVehicleDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VehNumLabelInViewVehicles, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VehNumFieldInViewVehicles, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchBtnInViewVehicles))
                .addGap(62, 62, 62)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        ViewVehicleTab.addTab("View Vehicles", ViewVehicleDetailsPanel);

        javax.swing.GroupLayout ViewVehiclesLayout = new javax.swing.GroupLayout(ViewVehicles);
        ViewVehicles.setLayout(ViewVehiclesLayout);
        ViewVehiclesLayout.setHorizontalGroup(
            ViewVehiclesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewVehiclesLayout.createSequentialGroup()
                .addComponent(ViewVehicleTab)
                .addContainerGap())
        );
        ViewVehiclesLayout.setVerticalGroup(
            ViewVehiclesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ViewVehicleTab)
        );

        VehicleDetailsCop.addTab("Vehicle Details", ViewVehicles);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 0, 0));
        jButton1.setText("Log Out");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(328, 328, 328)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(542, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(239, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 900, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 538, Short.MAX_VALUE))
        );

        VehicleDetailsCop.addTab("Log Out", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VehicleDetailsCop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VehicleDetailsCop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VehicleNumFieldInViewOffenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VehicleNumFieldInViewOffenceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VehicleNumFieldInViewOffenceActionPerformed

    private void PlaceFieldInRaiseOffenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlaceFieldInRaiseOffenceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PlaceFieldInRaiseOffenceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelBtnInClearOffence;
    private javax.swing.JButton CancelOffenceBtn;
    private javax.swing.JButton ClearOffenceBtn;
    private javax.swing.JPanel ClearOffencePanel;
    private javax.swing.JPanel ClearOffenceTab;
    private javax.swing.JTable ClearOffenceTable;
    private javax.swing.JLabel ClearOffenceTitle;
    private javax.swing.JLabel ImageLabelInRaiseOffence;
    private javax.swing.JTabbedPane ManageOffenceTab;
    private javax.swing.JPanel ManageOffences;
    private javax.swing.JLabel OffenceDetailsTitleInRaiseOffence;
    private javax.swing.JTextField OffenceIdFieldInRaiseOffence;
    private javax.swing.JLabel OffenceIdLabelInRaiseOffence;
    private javax.swing.JComboBox<String> OffenceStatusComboBoxInRaiseOffence;
    private javax.swing.JLabel OffenceStatusLabelInRaiseOffence;
    private javax.swing.JTable OffencesTableInViewOffence;
    private javax.swing.JPanel OwnerDetails;
    private javax.swing.JTabbedPane OwnerDetailsPane;
    private javax.swing.JPanel OwnerDetailsPanel;
    private javax.swing.JTable OwnerDetailsTable;
    private javax.swing.JLabel OwnerDetailsTitle;
    private javax.swing.JTextField PlaceFieldInRaiseOffence;
    private javax.swing.JLabel PlaceLabelInRaiseOffence;
    private javax.swing.JButton RaiseOffenceBtn;
    private javax.swing.JPanel RaiseOffencePanel;
    private javax.swing.JTextField ReportedByFieldInRaiseOffence;
    private javax.swing.JLabel ReportedByLabelInRaiseOffence;
    private javax.swing.JButton SearchBtnInClearOffence;
    private javax.swing.JButton SearchBtnInOwnerDetails;
    private javax.swing.JButton SearchBtnInViewOffence;
    private javax.swing.JButton SearchBtnInViewVehicles;
    private javax.swing.JLabel TimeLabelInRaiseOffence;
    private javax.swing.JSpinner TimeSpinnerInRaiseOffence;
    private javax.swing.JButton UploadImageBtn;
    private javax.swing.JTextField VehNumFieldInClearOffence;
    private javax.swing.JTextField VehNumFieldInRaiseOffence;
    private javax.swing.JTextField VehNumFieldInViewVehicles;
    private javax.swing.JLabel VehNumLabelInClearOffence;
    private javax.swing.JLabel VehNumLabelInRaiseOffence;
    private javax.swing.JLabel VehNumLabelInViewVehicles;
    private javax.swing.JTabbedPane VehicleDetailsCop;
    private javax.swing.JTable VehicleDetailsTableInViewVehicles;
    private javax.swing.JLabel VehicleDetailsTitle;
    private javax.swing.JTextField VehicleNumFieldInOwnerDetails;
    private javax.swing.JTextField VehicleNumFieldInViewOffence;
    private javax.swing.JLabel VehicleNumLabelInOwnerDetails;
    private javax.swing.JLabel VehicleNumLabelInViewOffence;
    private javax.swing.JPanel ViewOffencePanel;
    private javax.swing.JLabel ViewOffencesTitle;
    private javax.swing.JPanel ViewVehicleDetailsPanel;
    private javax.swing.JTabbedPane ViewVehicleTab;
    private javax.swing.JPanel ViewVehicles;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable4;
    // End of variables declaration//GEN-END:variables
}
